version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data
  node:
    build:
      context: ./exam-11-api
      dockerfile: dockerfile
    ports:
      - 9000:3000
    volumes:
      - ./exam-11-api:/app
    depends_on:
      - mongo
   
  react:
    build:
      context: ./exam-11-client
      dockerfile: Dockerfile
    ports:
      - 3000:8000
    volumes:
      - ./exam-11-client:/app
    

    